### ISSUE TITLE
Does version 0.3 fully support bloodhound 2.1?

### ISSUE THREAD

**Issue by sbroosnokia** [fox-it/bloodhound-import#10]
I was using 0.3 to import data in Bloodhound 2.0, but does this version also support all features of Bloodhoudn 2.1?

https://blog.cptjesus.com/posts/bloodhound21

**Comment by dirkjanm** [comment]
No not yet, let's keep this issue open until it does.

**Comment by sbroosnokia** [comment]
Hi, Any idea when the project will be updated for 2.1?

**Comment by mwgielen** [comment]
Unfortunately I've not been able to look into this and I don't have an ETA yet.

**Comment by PaperMtn** [comment]
Hi, just checking in whether there is any timeline for this to support Bloodhound 2.1?

**Comment by mwgielen** [comment]
No timeline yet

**Comment by mwgielen** [comment]
Version 0.4, on the dev branch should import bloodhound 2.1 files correctly.

**Comment by sbroosnokia** [comment]
It seems to work. Will this be integrated in the master branch?

Meanwhile bloodhound version 2.2.1 is released. Is this supported with the dev changes? Will this project be maintained or should we migrate?

**Comment by mwgielen** [comment]
Been working on version 3 support. This issue can be closed.
