### ISSUE TITLE
Python Error - "cannot import name cstruct"

### ISSUE THREAD

**Issue by weuroi578** [fox-it/bloodhound-import#5]
When I first attempted to run it the error was related to dissect. I installed it using pip install dissect.

Now I am receiving the error "ImportError: cannot import name cstruct" Below is the error output

Traceback (most recent call last):
  File "./bloodhound.py", line 3, in <module>
    import bloodhound
  File "/opt/BloodHound.py/bloodhound/__init__.py", line 28, in <module>
    from bloodhound.enumeration.computers import ComputerEnumerator
  File "/opt/BloodHound.py/bloodhound/enumeration/computers.py", line 30, in <module>
    from bloodhound.enumeration.memberships import MembershipEnumerator
  File "/opt/BloodHound.py/bloodhound/enumeration/memberships.py", line 33, in <module>
    from bloodhound.enumeration.acls import AclEnumerator, parse_binary_acl
  File "/opt/BloodHound.py/bloodhound/enumeration/acls.py", line 31, in <module>
    from dissect import cstruct
ImportError: cannot import name cstruct

Please help :(

**Comment by dirkjanm** [comment]
You need to use `pip install dissect.cstruct`, dissect itself is a different package

**Comment by dirkjanm** [comment]
Actually this should be in the BloodHound.py repository: https://github.com/fox-it/BloodHound.py
Closing it here, if you still have issues with this please open a new issue there.

**Comment by evilwing** [comment]
i am running in macosx,cannot solve it

**Comment by rkovaci** [comment]
the issue persists after installing dissect.cstruct as well. is there any workarounds for this by any chance?

**Comment by dirkjanm** [comment]
I've just pushed a change to BloodHound.py to include cstruct in the package, this should fix the issues for everyone. Please use latest bloodhound.py from master.
